#!/bin/bash

#######################################################
# 🚀 WALLONE - АВТОМАТИЧЕСКОЕ РАЗВЕРТЫВАНИЕ
#######################################################
# Скрипт для автоматического развертывания проекта
# на production сервере в один клик
#######################################################

set -e  # Остановка при ошибке

# Цвета для вывода
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Функции для красивого вывода
print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

print_header() {
    echo -e "\n${BLUE}═══════════════════════════════════════${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}═══════════════════════════════════════${NC}\n"
}

#######################################################
# ПРОВЕРКА ОКРУЖЕНИЯ
#######################################################

print_header "🔍 ПРОВЕРКА ОКРУЖЕНИЯ"

# Проверка наличия .env.deploy
if [ ! -f ".env.deploy" ]; then
    print_error "Файл .env.deploy не найден!"
    print_info "Создайте файл .env.deploy и заполните необходимые данные"
    exit 1
fi

# Загрузка конфигурации
print_info "Загрузка конфигурации из .env.deploy..."
source .env.deploy

# Проверка обязательных параметров
REQUIRED_VARS=("SERVER_IP" "DB_HOST" "DB_PASSWORD" "MAIL_PASSWORD" "FTP_PASSWORD" "ADMIN_EMAIL")
MISSING_VARS=()

for var in "${REQUIRED_VARS[@]}"; do
    if [ -z "${!var}" ]; then
        MISSING_VARS+=("$var")
    fi
done

if [ ${#MISSING_VARS[@]} -ne 0 ]; then
    print_error "Не заполнены обязательные параметры в .env.deploy:"
    for var in "${MISSING_VARS[@]}"; do
        echo "  - $var"
    done
    exit 1
fi

print_success "Все обязательные параметры заполнены"

# Генерация случайных ключей если не указаны
if [ -z "$REVERB_APP_KEY" ]; then
    REVERB_APP_KEY=$(openssl rand -base64 32)
    print_info "Сгенерирован REVERB_APP_KEY"
fi

if [ -z "$REVERB_APP_SECRET" ]; then
    REVERB_APP_SECRET=$(openssl rand -base64 32)
    print_info "Сгенерирован REVERB_APP_SECRET"
fi

# Проверка SSH доступа
print_info "Проверка SSH доступа к серверу $SERVER_IP..."

SSH_OPTS="-p $SSH_PORT -o ConnectTimeout=10 -o StrictHostKeyChecking=no"
if [ -n "$SSH_KEY_PATH" ]; then
    SSH_OPTS="$SSH_OPTS -i $SSH_KEY_PATH"
fi

if ! ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "echo 'SSH OK'" &> /dev/null; then
    print_error "Не удалось подключиться к серверу!"
    print_info "Проверьте параметры: SERVER_IP, SERVER_USER, SSH_PORT, SSH_KEY_PATH"
    exit 1
fi

print_success "SSH подключение успешно"

#######################################################
# ПОДТВЕРЖДЕНИЕ РАЗВЕРТЫВАНИЯ
#######################################################

print_header "📋 ПАРАМЕТРЫ РАЗВЕРТЫВАНИЯ"

echo "Сервер: $SERVER_USER@$SERVER_IP:$SSH_PORT"
echo "Домен: https://$MAIN_DOMAIN"
echo "WebSocket: wss://$WS_DOMAIN"
echo "База данных: $DB_DATABASE@$DB_HOST:${DB_PORT:-3306} (внешняя)"
echo "Email для SSL: $ADMIN_EMAIL"
echo ""

read -p "Продолжить развертывание? (yes/no): " -r
echo
if [[ ! $REPLY =~ ^[Yy][Ee][Ss]$ ]]; then
    print_warning "Развертывание отменено"
    exit 0
fi

#######################################################
# ПОДГОТОВКА ФАЙЛА .env
#######################################################

print_header "📝 ПОДГОТОВКА КОНФИГУРАЦИИ"

print_info "Создание .env файла..."

cat > .env.production.tmp << EOF
# Production Configuration - Auto-generated by deploy.sh
APP_NAME=Wallone
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=https://${MAIN_DOMAIN}
APP_FRONT_URL=https://wallone.app

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=error

DB_CONNECTION=mysql
DB_HOST=${DB_HOST}
DB_PORT=${DB_PORT:-3306}
DB_DATABASE=${DB_DATABASE}
DB_USERNAME=${DB_USERNAME}
DB_PASSWORD=${DB_PASSWORD}

FTP_HOST=${FTP_HOST}
FTP_USERNAME=${FTP_USERNAME}
FTP_PASSWORD=${FTP_PASSWORD}
FTP_URL=${FTP_URL}

GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT_URI=

YANDEX_CLIENT_ID=
YANDEX_CLIENT_SECRET=
YANDEX_REDIRECT_URI=

BROADCAST_DRIVER=reverb
CACHE_DRIVER=redis
FILESYSTEM_DISK=local
QUEUE_CONNECTION=redis
SESSION_DRIVER=redis
SESSION_LIFETIME=120

REDIS_HOST=redis
REDIS_PASSWORD=null
REDIS_PORT=6379
REDIS_CLIENT=phpredis

MAIL_MAILER=smtp
MAIL_HOST=${MAIL_HOST}
MAIL_PORT=${MAIL_PORT}
MAIL_USERNAME=${MAIL_USERNAME}
MAIL_PASSWORD=${MAIL_PASSWORD}
MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
MAIL_FROM_ADDRESS=${MAIL_USERNAME}
MAIL_FROM_NAME="\${APP_NAME}"

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

PASSPORT_PERSONAL_ACCESS_CLIENT_ID=
PASSPORT_PERSONAL_ACCESS_CLIENT_SECRET=
PASSPORT_PASSWORD_CLIENT_ID=
PASSPORT_PASSWORD_CLIENT_SECRET=

REVERB_APP_ID=533193
REVERB_APP_KEY=${REVERB_APP_KEY}
REVERB_APP_SECRET=${REVERB_APP_SECRET}

REVERB_SERVER_HOST=0.0.0.0
REVERB_SERVER_PORT=8080

REVERB_HOST=${WS_DOMAIN}
REVERB_PORT=443
REVERB_SCHEME=wss

VITE_APP_NAME="\${APP_NAME}"
VITE_REVERB_APP_KEY="\${REVERB_APP_KEY}"
VITE_REVERB_HOST="\${REVERB_HOST}"
VITE_REVERB_PORT="\${REVERB_PORT}"
VITE_REVERB_SCHEME="\${REVERB_SCHEME}"

TELESCOPE_ENABLED=false
INIT_DB=true
EOF

print_success ".env файл подготовлен"

#######################################################
# ПОДГОТОВКА СЕРВЕРА
#######################################################

print_header "🔧 ПОДГОТОВКА СЕРВЕРА"

print_info "Обновление системы..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "apt update" > /dev/null 2>&1

print_info "Установка Docker..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "bash -s" << 'ENDSSH'
# Установка Docker если его нет
if ! command -v docker &> /dev/null; then
    curl -fsSL https://get.docker.com -o get-docker.sh
    sh get-docker.sh
    rm get-docker.sh
fi

# Установка Docker Compose plugin
if ! docker compose version &> /dev/null; then
    apt install -y docker-compose-plugin
fi
ENDSSH

print_success "Docker установлен"

if [ "$INSTALL_MONITORING" = "true" ]; then
    print_info "Установка дополнительных утилит..."
    ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "apt install -y git curl wget nano htop ufw fail2ban" > /dev/null 2>&1
    print_success "Утилиты установлены"
fi

print_info "Настройка firewall..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "bash -s" << 'ENDSSH'
# Настройка UFW
if command -v ufw &> /dev/null; then
    ufw --force enable
    ufw allow 22/tcp
    ufw allow 80/tcp
    ufw allow 443/tcp
    ufw allow 443/udp
fi
ENDSSH

print_success "Firewall настроен"

#######################################################
# КОПИРОВАНИЕ ФАЙЛОВ
#######################################################

print_header "📦 КОПИРОВАНИЕ ФАЙЛОВ"

print_info "Создание директории на сервере..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "mkdir -p /var/www/wallone"

print_info "Копирование файлов проекта (это может занять несколько минут)..."

# Создаем временный архив для быстрой передачи
tar -czf wallone-temp.tar.gz \
    --exclude='node_modules' \
    --exclude='vendor' \
    --exclude='.git' \
    --exclude='storage/logs/*' \
    --exclude='bootstrap/cache/*' \
    --exclude='wallone-temp.tar.gz' \
    .

# Копируем архив на сервер
scp $SSH_OPTS wallone-temp.tar.gz $SERVER_USER@$SERVER_IP:/tmp/

# Распаковываем на сервере
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "bash -s" << 'ENDSSH'
cd /var/www/wallone
tar -xzf /tmp/wallone-temp.tar.gz
rm /tmp/wallone-temp.tar.gz
ENDSSH

# Удаляем локальный архив
rm wallone-temp.tar.gz

print_success "Файлы скопированы"

# Копируем подготовленный .env файл
print_info "Копирование конфигурации..."
scp $SSH_OPTS .env.production.tmp $SERVER_USER@$SERVER_IP:/var/www/wallone/.env
rm .env.production.tmp

print_success "Конфигурация скопирована"

#######################################################
# ЗАПУСК ПРИЛОЖЕНИЯ
#######################################################

print_header "🚀 ЗАПУСК ПРИЛОЖЕНИЯ"

print_info "Сборка Docker образов (это может занять 5-10 минут)..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "bash -s" << 'ENDSSH'
cd /var/www/wallone
docker compose -f docker-compose.production.yml build --no-cache
ENDSSH

print_success "Образы собраны"

print_info "Запуск контейнеров..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "bash -s" << 'ENDSSH'
cd /var/www/wallone
docker compose -f docker-compose.production.yml up -d
ENDSSH

print_success "Контейнеры запущены"

print_info "Ожидание инициализации приложения (60 секунд)..."
sleep 60

# Проверка статуса контейнеров
print_info "Проверка статуса контейнеров..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "cd /var/www/wallone && docker compose -f docker-compose.production.yml ps"

# Отключаем INIT_DB после первого запуска
print_info "Отключение режима инициализации..."
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "sed -i 's/INIT_DB=true/INIT_DB=false/' /var/www/wallone/.env"
ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "cd /var/www/wallone && docker compose -f docker-compose.production.yml restart app"

print_success "Режим инициализации отключен"

#######################################################
# НАСТРОЙКА BACKUP (опционально)
#######################################################

if [ "$SETUP_BACKUP" = "true" ]; then
    print_header "💾 НАСТРОЙКА АВТОМАТИЧЕСКОГО BACKUP"

    print_info "Создание директории для backup..."
    ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "mkdir -p /backup"

    print_info "Настройка cron для ежедневного backup..."
    ssh $SSH_OPTS $SERVER_USER@$SERVER_IP "bash -s" << ENDSSH
# Добавляем задачу в cron для backup внешней БД
(crontab -l 2>/dev/null || echo "") | grep -v "wallone backup" | cat - << 'CRON' | crontab -
# Wallone backup - каждый день в 2:00 ночи (внешняя БД)
0 2 * * * mysqldump -h ${DB_HOST} -P ${DB_PORT:-3306} -u ${DB_USERNAME} -p'${DB_PASSWORD}' ${DB_DATABASE} > /backup/wallone_\$(date +\\%Y\\%m\\%d).sql 2>&1
# Очистка старых backup (старше 7 дней)
0 3 * * * find /backup -name "wallone_*.sql" -mtime +7 -delete 2>&1
CRON
ENDSSH

    print_success "Автоматический backup настроен (внешняя БД)"
    print_warning "Убедитесь что на сервере установлен mysql-client: apt install mysql-client"
fi

#######################################################
# ЗАВЕРШЕНИЕ
#######################################################

print_header "✅ РАЗВЕРТЫВАНИЕ ЗАВЕРШЕНО!"

echo ""
print_success "Ваше приложение успешно развернуто!"
echo ""
echo "═══════════════════════════════════════"
echo "📍 ИНФОРМАЦИЯ О ПРИЛОЖЕНИИ:"
echo "═══════════════════════════════════════"
echo ""
echo "🌐 Основной сайт:    https://${MAIN_DOMAIN}"
echo "🔌 WebSocket:        wss://${WS_DOMAIN}"
echo "📧 Email для SSL:    ${ADMIN_EMAIL}"
echo ""
echo "═══════════════════════════════════════"
echo "🔑 УЧЕТНЫЕ ДАННЫЕ:"
echo "═══════════════════════════════════════"
echo ""
echo "База данных (внешняя):"
echo "  - Хост:            ${DB_HOST}:${DB_PORT:-3306}"
echo "  - Имя БД:          ${DB_DATABASE}"
echo "  - Пользователь:    ${DB_USERNAME}"
echo "  - Пароль:          ${DB_PASSWORD}"
echo ""
echo "═══════════════════════════════════════"
echo "📝 СЛЕДУЮЩИЕ ШАГИ:"
echo "═══════════════════════════════════════"
echo ""
echo "1. Подождите 2-3 минуты пока Caddy получит SSL сертификаты"
echo "2. Откройте https://${MAIN_DOMAIN} в браузере"
echo "3. Проверьте работу WebSocket: wss://${WS_DOMAIN}"
echo "4. Проверьте логи: ssh $SERVER_USER@$SERVER_IP 'cd /var/www/wallone && docker compose -f docker-compose.production.yml logs'"
echo ""

if [ "$SETUP_BACKUP" = "true" ]; then
    echo "✓ Автоматический backup БД настроен (ежедневно в 2:00)"
    echo "  Backup хранятся в /backup/ на сервере"
    echo ""
fi

print_warning "ВАЖНО: Сохраните учетные данные в надежном месте!"
echo ""
print_info "Для просмотра логов выполните:"
echo "  ssh $SERVER_USER@$SERVER_IP 'cd /var/www/wallone && docker compose -f docker-compose.production.yml logs -f'"
echo ""
print_info "Для просмотра статуса контейнеров:"
echo "  ssh $SERVER_USER@$SERVER_IP 'cd /var/www/wallone && docker compose -f docker-compose.production.yml ps'"
echo ""

print_success "🎉 Готово! Приятного использования!"
